# Generated by Django 2.2.1 on 2019-08-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='category_image',
            field=models.ImageField(default='category/default.png', upload_to='category/'),
        ),
    ]
